### ISSUE TITLE
Phase III Lab/Experiment(s) OnBoarding Request - Basics of Physics IITK

### ISSUE THREAD

**Issue by jaimathur** [virtual-labs/engineers-forum#592]
## *Lab OnBoarding Request*
Use this to register your lab for hosting or update the list
of experiments in the lab.

  - [ ] update existing hosting requirements, 

1. **Lab Repository**: https://github.com/virtual-labs/basics-of-physics-iitk

#### Optional
Fill this field to list the experiments that the lab should include

1. **List of Experiments and Repositories**: 
| No.| Experiment Name | Experiment repository URL |
[basics_of_physics.pdf](https://github.com/virtual-labs/engineers-forum/files/4759703/basics_of_physics.pdf)

**Comment by sravanthimodepu** [comment]
@jaimathur , please approve the following information

**Repo Owner Details**

Name - Kantesh Balani
GitHub handle - 
Email id - kbalani@iitk.ac.in

**Experiment Name Source URL Branch Tag Build Command**

1. Carey Foster’s Bridge to Measure Specific Resistance of Material - http://vlabs.iitb.ac.in/gitlab/iitk-labs/basics-of-physics-iitk/carey-foster-bridge-iitk, Master Branch, v1.0.0, make all

2. Energy Band Gap of Semiconductor- http://vlabs.iitb.ac.in/gitlab/iitk-labs/basics-of-physics-iitk/energy-band-gap-iitk, Master Branch, v1.0.0, make all

3. Radiation with Temperature Change Using Stefan’s Law - http://vlabs.iitb.ac.in/gitlab/iitk-labs/basics-of-physics-iitk/stefans-law-iitk, Master Branch, v1.0.0, make all

4. Finding Viscosity of Liquid by Rotating Cylinder Method - http://vlabs.iitb.ac.in/gitlab/iitk-labs/basics-of-physics-iitk/liquid-viscosity-iitk, Master Branch, v1.0.0, make all

5. Measurement of the wavelength of monochromatic source of light with the
help of Fresnel’s Bi prism - http://vlabs.iitb.ac.in/gitlab/iitk-labs/basics-of-physics-iitk/fresnel-biprism-iitk, Master Branch, v1.0.0, make all

6. Measurement of focal length of the combination of the two lenses separated
by a distance - http://vlabs.iitb.ac.in/gitlab/iitk-labs/basics-of-physics-iitk/focal-length-measurement-iitk, Master Branch, v1.0.0, make all


7. To measure specific rotation of cane sugar using Polarimeter - http://vlabs.iitb.ac.in/gitlab/iitk-labs/basics-of-physics-iitk/cane-sugar-rotation-iitk, Master Branch, v1.0.0, make all

8. Measurement of high resistance by the method of leakage of condenser - hhttp://vlabs.iitb.ac.in/gitlab/iitk-labs/basics-of-physics-iitk/condenser-leakage-method-iitk, Master Branch, v1.0.0, make all

9. To study polarization of light using He-Ne Laser -http://vlabs.iitb.ac.in/gitlab/iitk-labs/basics-of-physics-iitk/he-ne-laser-polarization-iitk, Master Branch, v1.0.0, make all

10. Measurement of Numerical aperture and attenuation constant of optical fibre - http://vlabs.iitb.ac.in/gitlab/iitk-labs/basics-of-physics-iitk/numerical-aperture-measurement-iitk, Master Branch, v1.0.0, make all

**Comment by jaimathur** [comment]
@priya100raman @sravanthimodepu 
Yes. It's fine.

**Comment by sravanthimodepu** [comment]
@jaimathur

Hosted URL of Lab: http://bop-iitk.vlabs.ac.in/
Branch: Master
Tag: v1.0.0

Please get it approved by the owner

**Comment by priya100raman** [comment]
@jaimathur, we notice that many of the experiments do not have content in their Aim pages and  Theory & Procedure is empty for all the experiments.  Please bring it to the notice of the developer.

**Comment by s0h8** [comment]
@pavanchow 
Kindly re host the following experiments

1.Carey Foster’s Bridge to Measure Specific Resistance of Material - https://github.com/virtual-labs/exp-carey-foster-bridge-iitk, Master Branch, v1.0.0

2.Energy Band Gap of Semiconductor- https://github.com/virtual-labs/exp-energy-band-gap-iitk, Master Branch, v1.0.0

3.Finding Viscosity of Liquid by Rotating Cylinder Method - https://github.com/virtual-labs/exp-liquid-viscosity-iitk, Master Branch, v1.0.1

4.Measurement of the wavelength of monochromatic source of light with the
help of Fresnel’s Bi prism - https://github.com/virtual-labs/exp-fresnel-biprism-iitk, Master Branch, v1.0.0, 

5.Measurement of focal length of the combination of the two lenses separated
by a distance - https://github.com/virtual-labs/exp-focal-length-measurement-iitk, Master Branch, v1.0.0

6.To measure specific rotation of cane sugar using Polarimeter - https://github.com/virtual-labs/exp-cane-sugar-rotation-iitk, Master Branch, v1.0.0

7.Measurement of high resistance by the method of leakage of condenser - https://github.com/virtual-labs/exp-condenser-leakage-method-iitk, Master Branch, v1.0.0

8.To study polarization of light using He-Ne Laser -https://github.com/virtual-labs/exp-he-ne-laser-polarization-iitk, Master Branch, v1.0.0

9.Measurement of Numerical aperture and attenuation constant of optical fibre - https://github.com/virtual-labs/exp-numerical-aperture-measurement-iitk, Master Branch, v1.0.0

**Comment by pavanchow** [comment]
@s0h8 
Hosted Basics of Physics Lab with mentioned experiments
URL: http://bop-iitk.vlabs.ac.in/

Please check and approve.

**Comment by umraodhananjay** [comment]
**Simulator design is not appearing on hosted links..** 
Exp 7. https://bop-iitk.vlabs.ac.in/exp/condenser-leakage-method/simulation.html
Exp 9. https://bop-iitk.vlabs.ac.in/exp/numerical-aperture-measurement/simulation.html

But these are running nicely on testing links.. 

Exp 7. https://virtual-labs.github.io/exp-numerical-aperture-measurement-iitk/simulation.html
Exp 9. https://virtual-labs.github.io/exp-condenser-leakage-method-iitk/simulation.html

**Comment by s0h8** [comment]
@pavanchow  
kindly re host the following experiments
Finding Viscosity of Liquid by Rotating Cylinder Method - https://github.com/virtual-labs/exp-liquid-viscosity-iitk, Master Branch, v1.0.2
Measurement of high resistance by the method of leakage of condenser - https://github.com/virtual-labs/exp-condenser-leakage-method-iitk, Master Branch, v1.0.3

**Comment by pavanchow** [comment]
@s0h8
Hosted Basics of Physics Lab with mentioned experiments
URL: http://bop-iitk.vlabs.ac.in/

Please check and approve.

**Comment by umraodhananjay** [comment]
@pavanchow

these links are not working..
Exp 7. https://bop-iitk.vlabs.ac.in/exp/condenser-leakage-method/simulation.html
Exp 9. https://bop-iitk.vlabs.ac.in/exp/numerical-aperture-measurement/simulation.html

**Comment by pavanchow** [comment]
@umraodhananjay Your commits on the main branch was 1 day ago and the testing branch was 1 month ago. Sources from the testing branch are working fine which might have correct sources.
And please follow this process: push to **[dev](https://github.com/virtual-labs/exp-numerical-aperture-measurement-iitk/tree/dev)** -> then to **[testing](https://github.com/virtual-labs/exp-numerical-aperture-measurement-iitk/tree/testing)** (for testing) -> then to deploy to vlabs site **[main](https://github.com/virtual-labs/exp-numerical-aperture-measurement-iitk/tree/testing)**

![image](https://user-images.githubusercontent.com/24794698/108198977-5b641d00-7142-11eb-92aa-48fdcf32db02.png)

**Comment by s0h8** [comment]
kindly rehost the following experiments , all the branches has been updated
1.Measurement of Numerical aperture and attenuation constant of optical fibre - https://github.com/virtual-labs/exp-numerical-aperture-measurement-iitk, Master Branch, v1.0.1
2.Measurement of high resistance by the method of leakage of condenser - https://github.com/virtual-labs/exp-condenser-leakage-method-iitk, Master Branch, v1.0.3

**Comment by pavanchow** [comment]
@s0h8 rehosted Measurement of Numerical aperture and attenuation constant of optical fiber and  Measurement of high resistance by the method of leakage of condenser experiments. 

URL: http://bop-iitk.vlabs.ac.in/

Please check and approve.

**Comment by s0h8** [comment]
Kindly re host the following experiments 
1.Carey Foster’s Bridge to Measure Specific Resistance of Material - https://github.com/virtual-labs/exp-carey-foster-bridge-iitk, Master Branch, v1.0.2
2.Measurement of focal length of the combination of the two lenses separated
by a distance - https://github.com/virtual-labs/exp-focal-length-measurement-iitk, Master Branch, v1.0.1
3.Energy Band Gap of Semiconductor- https://github.com/virtual-labs/exp-energy-band-gap-iitk, Master Branch, v1.0.1
4.Measurement of the wavelength of monochromatic source of light with the
help of Fresnel’s Bi prism - https://github.com/virtual-labs/exp-fresnel-biprism-iitk, Master Branch, v1.0.1
5.To study polarization of light using He-Ne Laser -https://github.com/virtual-labs/exp-he-ne-laser-polarization-iitk, Master Branch, v1.0.1

**Comment by pavanchow** [comment]
@s0h8 
Hosted above mentioned experiments
URL: http://bop-iitk.vlabs.ac.in/

Please check and approve.

**Comment by umraodhananjay** [comment]
@pavanchow @priya100raman 

We have completed Stefen's Law experiment, Kindly rehost this.

Radiation with Temperature Change Using Stefan’s Law - http://vlabs.iitb.ac.in/gitlab/iitk-labs/basics-of-physics-iitk/stefans-law-iitk, Master Branch, v1.0.1

**Comment by priya100raman** [comment]
@s0h8 @umraodhananjay  the lab has been rehosted. Please check if all the experiments are working and  state your approval in this issue

**Comment by s0h8** [comment]
check and approved all the 10 experiments of Basics of Physics. Kindly add all experiments in the main site

**Comment by s0h8** [comment]
@pavanchow Kindly rehost the following experiment 
1.Carey Foster’s Bridge to Measure Specific Resistance of Material - https://github.com/virtual-labs/exp-carey-foster-bridge-iitk, Master Branch, v1.0.3

2.Energy Band Gap of Semiconductor- https://github.com/virtual-labs/exp-energy-band-gap-iitk, Master Branch, v1.0.2

3.Radiation with Temperature Change Using Stefan’s Law - https://github.com/virtual-labs/exp-stefans-law-iitk, Master Branch, v1.0.2

4.Finding Viscosity of Liquid by Rotating Cylinder Method - https://github.com/virtual-labs/exp-liquid-viscosity-iitk, Master Branch, v1.0.3

5.Measurement of the wavelength of monochromatic source of light with the
help of Fresnel’s Bi prism - https://github.com/virtual-labs/exp-fresnel-biprism-iitk, Master Branch, v1.0.2

6.Measurement of focal length of the combination of the two lenses separated
by a distance - https://github.com/virtual-labs/exp-focal-length-measurement-iitk, Master Branch, v1.0.2

7.To measure specific rotation of cane sugar using Polarimeter - https://github.com/virtual-labs/exp-cane-sugar-rotation-iitk, Master Branch, v1.0.1

8.Measurement of high resistance by the method of leakage of condenser - https://github.com/virtual-labs/exp-condenser-leakage-method-iitk, Master Branch, v1.0.4

9.To study polarization of light using He-Ne Laser -https://github.com/virtual-labs/exp-he-ne-laser-polarization-iitk, Master Branch, v1.0.2

10.Measurement of Numerical aperture and attenuation constant of optical fibre - https://github.com/virtual-labs/exp-numerical-aperture-measurement-iitk, Master Branch, v1.0.2

**Comment by pavanchow** [comment]
@s0h8
Hosted lab with above-mentioned experiments
URL: https://bop-iitk.vlabs.ac.in/

Please check and approve.

**Comment by s0h8** [comment]
@pavanchow  The following two experiments are not appearing properly, in Stefan's law pop up is still not appearing in simulator but it appears in actual simulator and in liquid viscosity the simulator is  getting cut not fully visible. 
1.Radiation with Temperature Change Using Stefan’s Law - https://github.com/virtual-labs/exp-stefans-law-iitk, Master Branch, v1.0.2
2.Finding Viscosity of Liquid by Rotating Cylinder Method - https://github.com/virtual-labs/exp-liquid-viscosity-iitk, Master Branch, v1.0.3

**Comment by pavanchow** [comment]
@s0h8
Hosted lab with **Radiation with Temperature Change Using Stefan’s Law** (v1.0.2)  and **Finding Viscosity of Liquid by Rotating Cylinder Method** (v1.0.3) experiments
URL: https://bop-iitk.vlabs.ac.in/

Please check and approve.

**Comment by s0h8** [comment]
This we hosted in our local server and it is working fine, it shows the pop up
![stefan1](https://user-images.githubusercontent.com/15856050/109288997-96093c00-784b-11eb-85a9-a4284ea4ad60.PNG)

**Comment by s0h8** [comment]
@pavanchow  but in vlab site pop up is not appearing in stefan law simulator

**Comment by s0h8** [comment]
@pavanchow kindly re host the following simulator
Finding Viscosity of Liquid by Rotating Cylinder Method - https://github.com/virtual-labs/exp-liquid-viscosity-iitk, Master Branch, v1.0.4

**Comment by pavanchow** [comment]
@s0h8 For better security practices, phase 3 experiments can only be accessed on HTTPS protocol but some Basics of Physics experiments contain HTTP links and the same thing is breaking the pop up in Stefan's law simulator. Can you please change HTTP to HTTPS? 
 
 You can find the same in the console window of below screenshot,
![stefan-law](https://user-images.githubusercontent.com/24794698/109448173-5882f980-7a6b-11eb-9c09-ae3fa437d55a.png)

**Comment by pavanchow** [comment]
@s0h8
Hosted lab with Finding Viscosity of Liquid by Rotating Cylinder Method (v1.0.4) experiment
URL: https://bop-iitk.vlabs.ac.in/

Please check and approve.

**Comment by s0h8** [comment]
@pavanchow
all the links has been modified , kindly re host the experiment
Radiation with Temperature Change Using Stefan’s Law - https://github.com/virtual-labs/exp-stefans-law-iitk, Master Branch, v1.0.3

**Comment by pavanchow** [comment]
@s0h8
Hosted lab with Radiation with Temperature Change Using Stefan’s Law (v1.0.3) experiment
URL: https://bop-iitk.vlabs.ac.in/

Please check and approve.

**Comment by s0h8** [comment]
@pavanchow   Some slight modification  done in below experiment also, kindly re host
Energy Band Gap of Semiconductor- https://github.com/virtual-labs/exp-energy-band-gap-iitk, Master Branch, v1.0.3

**Comment by s0h8** [comment]
@pavanchow  Radiation with Temperature Change Using Stefan’s Law (v1.0.3) experiment is checked and approved

**Comment by pavanchow** [comment]
@s0h8
Hosted lab with Energy Band Gap of Semiconductor (v1.0.3) experiment
URL: https://bop-iitk.vlabs.ac.in/

Please check and approve.

**Comment by s0h8** [comment]
@pavanchow  Hosted lab with Energy Band Gap of Semiconductor (v1.0.3) experiment is checked and approved

**Comment by s0h8** [comment]
@pavanchow Kindly re host the following experiments
1.Carey Foster’s Bridge to Measure Specific Resistance of Material - https://github.com/virtual-labs/exp-carey-foster-bridge-iitk, Master Branch, v1.0.4

2.Energy Band Gap of Semiconductor- https://github.com/virtual-labs/exp-energy-band-gap-iitk, Master Branch, v1.0.4

3.Radiation with Temperature Change Using Stefan’s Law - https://github.com/virtual-labs/exp-stefans-law-iitk, Master Branch, v1.0.4

4.Finding Viscosity of Liquid by Rotating Cylinder Method - https://github.com/virtual-labs/exp-liquid-viscosity-iitk, Master Branch, v1.0.5

5.Measurement of the wavelength of monochromatic source of light with the
help of Fresnel’s Bi prism - https://github.com/virtual-labs/exp-fresnel-biprism-iitk, Master Branch, v1.0.3

6.Measurement of focal length of the combination of the two lenses separated
by a distance - https://github.com/virtual-labs/exp-focal-length-measurement-iitk, Master Branch, v1.0.3

7.To measure specific rotation of cane sugar using Polarimeter - https://github.com/virtual-labs/exp-cane-sugar-rotation-iitk, Master Branch, v1.0.2

8.Measurement of high resistance by the method of leakage of condenser - https://github.com/virtual-labs/exp-condenser-leakage-method-iitk, Master Branch, v1.0.5

9.To study polarization of light using He-Ne Laser -https://github.com/virtual-labs/exp-he-ne-laser-polarization-iitk, Master Branch, v1.0.3

10.Measurement of Numerical aperture and attenuation constant of optical fibre - https://github.com/virtual-labs/exp-numerical-aperture-measurement-iitk, Master Branch, v1.0.3

**Comment by pavanchow** [comment]
@s0h8
Hosted Basics of Physics lab with mentioned experiment tags
URL: https://bop-iitk.vlabs.ac.in/

Please check and approve.

**Comment by s0h8** [comment]
@pavanchow I Checked the link , updated data is not shown for any experiment

**Comment by s0h8** [comment]
@pavanchow  updated data is not shown for any experiment in the given link

**Comment by pavanchow** [comment]
@s0h8 We are looking into this issue and will update you once fixed.

**Comment by BalammaBoya** [comment]
@pavanchow Kindly re host the following experiments

1.Carey Foster’s Bridge to Measure Specific Resistance of Material - https://github.com/virtual-labs/exp-carey-foster-bridge-iitk, Master Branch, v1.0.5

2.Energy Band Gap of Semiconductor- https://github.com/virtual-labs/exp-energy-band-gap-iitk, Master Branch, v1.0.5

3.Radiation with Temperature Change Using Stefan’s Law - https://github.com/virtual-labs/exp-stefans-law-iitk, Master Branch, v1.0.5

4.Finding Viscosity of Liquid by Rotating Cylinder Method - https://github.com/virtual-labs/exp-liquid-viscosity-iitk, Master Branch, v1.0.6

5.Measurement of the wavelength of monochromatic source of light with the help of Fresnel’s Bi prism - https://github.com/virtual-labs/exp-fresnel-biprism-iitk, Master Branch, v1.0.4

6.Measurement of focal length of the combination of the two lenses separated by a distance - https://github.com/virtual-labs/exp-focal-length-measurement-iitk, Master Branch, v1.0.4

7.To measure specific rotation of cane sugar using Polarimeter - https://github.com/virtual-labs/exp-cane-sugar-rotation-iitk, Master Branch, v1.0.3

8.Measurement of high resistance by the method of leakage of condenser - https://github.com/virtual-labs/exp-condenser-leakage-method-iitk, Master Branch, v1.0.6

9.To study polarization of light using He-Ne Laser -https://github.com/virtual-labs/exp-he-ne-laser-polarization-iitk, Master Branch, v1.0.4

10.Measurement of Numerical aperture and attenuation constant of optical fibre - https://github.com/virtual-labs/exp-numerical-aperture-measurement-iitk, Master Branch, v1.0.4

**Comment by pavanchow** [comment]
@s0h8 We found merge conflicts on the last commit and we fixed the conflicts. 

Hosted Basics of Physics lab 
URL: https://bop-iitk.vlabs.ac.in/

Can you please check and approve?

**Comment by s0h8** [comment]
@pavanchow  <sup> tag is not working in some experiments.

**Comment by pavanchow** [comment]
@s0h8 Can you please mention which experiments are not working?

**Comment by s0h8** [comment]
1.Carey Foster’s Bridge to Measure Specific Resistance of Material - https://github.com/virtual-labs/exp-carey-foster-bridge-iitk, Master Branch, v1.0.5

2.Energy Band Gap of Semiconductor- https://github.com/virtual-labs/exp-energy-band-gap-iitk, Master Branch, v1.0.5
Finding Viscosity of Liquid by Rotating Cylinder Method - https://github.com/virtual-labs/exp-liquid-viscosity-iitk, Master Branch, v1.0.6
5.Measurement of the wavelength of monochromatic source of light with the help of Fresnel’s Bi prism - https://github.com/virtual-labs/exp-fresnel-biprism-iitk, Master Branch, v1.0.4
7.To measure specific rotation of cane sugar using Polarimeter - https://github.com/virtual-labs/exp-cane-sugar-rotation-iitk, Master Branch, v1.0.3
9.To study polarization of light using He-Ne Laser -https://github.com/virtual-labs/exp-he-ne-laser-polarization-iitk, Master Branch, v1.0.4
10.Measurement of Numerical aperture and attenuation constant of optical fibre - https://github.com/virtual-labs/exp-numerical-aperture-measurement-iitk, Master Branch, v1.0.4

**Comment by s0h8** [comment]
@pavanchow for the above mentioned experiments pre test and post test questions have the issue

**Comment by s0h8** [comment]
![Inkedexp_phy_LI](https://user-images.githubusercontent.com/15856050/119149083-ca674f80-ba6a-11eb-9354-fd4799dd30e6.jpg)

**Comment by s0h8** [comment]
@pavanchow in the above image, pretest should be pre test and posttest should be post test

**Comment by priya100raman** [comment]
@s0h8, pretest, and posttest are compound words and we fixed them to be that way in our later UI builds. Earlier, you saw it as pre test and post test since your experiments were hosted when the fix was not made.

**Comment by s0h8** [comment]
@pavanchow  Is lab hosted ?

**Comment by pavanchow** [comment]
@s0h8 Yes, the lab has been rehosted.

**Comment by s0h8** [comment]
@pavanchow I checked the hosted lab, the superscript and subscript tag errors are still there in experiments that I mentioned previously.

**Comment by BalammaBoya** [comment]
@s0h8 Yes, that is json issue, I will fix them.

**Comment by BalammaBoya** [comment]
@s0h8 Pretest and Posttests issues fixed. Please check and approve.

![Screenshot from 2021-06-02 19-33-16](https://user-images.githubusercontent.com/22425444/120493204-60d73180-c3d8-11eb-81ea-2e572cb38640.png)

**Comment by s0h8** [comment]
@BalammaBoya  In the below image correct the name of experiment no 4 , it is Finding Viscosity of liquid only
![image](https://user-images.githubusercontent.com/15856050/120523873-119efa00-c3f4-11eb-8154-e1fc7e6010e6.png)

**Comment by ravikiran2020** [comment]
Rehosting the lab with Bug Report and Rating Feature

**Comment by ravikiran2020** [comment]
Re-hosting the lab

**Comment by vlabiitk** [comment]
@ravikiran2020 Kindly provide access in this lab.

**Comment by ravikiran2020** [comment]
@vlabiitk Access granted. Please check.

**Comment by vlabiitk** [comment]
@ravikiran2020 
Please re-host below experiment :
1. Energy Band Gap of Semiconductor- https://github.com/virtual-labs/exp-energy-band-gap-iitk, Master Branch, v1.0.6

**Comment by ravikiran2020** [comment]
@vlabiitk Lab is re-hosted successfully.
